services:
    #listeners 
    baseListener:
        class: Renaissance\WebBundle\Listener\BaseListener
        arguments: [@service_container]
    registerListener:
        class: Renaissance\WebBundle\Listener\RegisterListener
        parent: baseListener
