security:
    providers:
        administrators:
            entity: { class: RenaissanceCommonBundle:User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        my_firewall:
            pattern: ^/
            anonymous: ~
            trusted_sso:
                manager: admin_sso
                login_action: false         # BeSimpleSsoAuthBundle:TrustedSso:login
                logout_action: false        # BeSimpleSsoAuthBundle:TrustedSso:logout
                create_users: true
                created_users_roles: [ROLE_USER ]
                check_path: /
        default:
            anonymous: ~
    access_control:
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/login, roles: ROLE_USER }
        - { path: ^/course/.*/with_user, roles: ROLE_USER }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

